[package]
name = "claude-proxy-worker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
worker = "0.0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
